In [19]:
import numpy as nm  
import pandas as pd  
from sklearn.preprocessing import StandardScaler   
from sklearn.model_selection import train_test_split 
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import accuracy_score
data_set=pd.read_csv('iris.csv')
x= data_set.iloc[:,[2,3]].values  
y= data_set.iloc[:, 4].values    
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.25, random_state=0)    
st_x= StandardScaler()  
x_train= st_x.fit_transform(x_train)    
x_test= st_x.transform(x_test)     
classifier= DecisionTreeClassifier(criterion='entropy', random_state=0)  
classifier.fit(x_train, y_train) 
y_pred= classifier.predict(x_test)   
cm= confusion_matrix(y_test, y_pred) 
print('Confusion matrix:\n',cm)
print("Accuracy:",accuracy_score(y_test,y_pred))


Confusion matrix:
 [[13  0  0]
 [ 0 15  1]
 [ 0  1  8]]
Accuracy: 0.9473684210526315
